# Generated by Django 6.0.4 on 2026-04-20 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('estat', models.CharField(choices=[('INIT', 'Inicial'), ('DISPONIBLE', 'Disponible'), ('ACTUALITZABLE', 'Actualitzable')], default='INIT', max_length=20)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_actualitzacio', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imatge', models.ImageField(upload_to='imatges/')),
                ('tipus', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada')], default='PUBLICA', max_length=10)),
                ('es_publica', models.BooleanField(default=True)),
                ('data_pujada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='api.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_actualitzacio', models.DateTimeField(auto_now=True)),
                ('etiquetes', models.ManyToManyField(blank=True, to='api.etiqueta')),
                ('expo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.expo')),
                ('imatge_destacada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.imatge')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto_enviada', models.ImageField(upload_to='intents/')),
                ('resultat_identificacio', models.TextField(blank=True, null=True)),
                ('data_intent', models.DateTimeField(auto_now_add=True)),
                ('expo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expo')),
                ('usuari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item_identificat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.item')),
            ],
        ),
        migrations.AddField(
            model_name='imatge',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imatges', to='api.item'),
        ),
    ]
