# Generated by Django 6.0.4 on 2026-04-24 13:53
# Generated by Django 6.0.4 on 2026-04-24 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='propietari',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
