# Generated by Django 5.2.13 on 2026-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expo_lenguaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='current_train',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('OK', 'Ok'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled'), ('REPLACE', 'Replace')], default='IDLE', max_length=20),
        ),
    ]
